name = "SailorMoon"
uuid = "546ee66a-3149-45bb-ad33-e73eeabd5078"
authors = ["yuri@tux <yuri.shimane@gmail.com>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
